blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
]

photowall/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(24)
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post


def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/post_list.html', {
        'post_list': post_list,
    })

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {
        'post': post,
    })

blog/templates/blog/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    {#<link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"/>#}
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootswatch/4.1.2/cosmo/bootstrap.min.css">
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script> 
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script> 
    {% block extra_head %}{% endblock %}
    <title>{% block title %}PhotoWall{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block extra_head %}
<style>
    .post_photo {
        max-width: 100%;
    }
</style>
{% endblock%}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card-header">
                    {{ post.title }}
                </div>
                <div class="card-body">
                    {% if post.photo %}
                        <img src="{{ post.photo.url }}" class="post_photo" />
                    {% endif %}
                    <hr/>
                    {{ post.content | linebreaks }}
                </div>
                <div class="card-footer">
                    <a href="{% url "blog:index" %}" class="btn btn-defalut">목록으로</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <h1>PhotoWall</h1>

    <ul>
    {% for post in post_list %}
    <li>
        <a href="{% url "blog:post_detail" post.pk %}">
            {{ post.title }}
        </a>
    </li>
    {% endfor %}
    </ul>
{% endblock %}